keys:
  - &khoa age1g2frg3jxdgv5xlrfca7qg7mmyzsw2vw90ygck8taya4cqk69wggqkyapgp
  - &sakaki age1weelnn60djp6fvqm6xn3y02r4prkwz2e94rpjc653hy74fq5tv7sg9lrk5
  - &chiyo age1epjexgpxcrp7nspsg45v76nkn54trmmzgzu6zc9md37mv007nfyqas87yt
  - &osaka age1hqw5zp8eg0h9fus9524pun6mfe39p987uewk5yr4yxs2peezuqfqc6qrmg
  - &yomi-strix age15tg98m0jy7tfj30ultxe4tg6uprgtcqa0mvv6pmme4jclwh0rptsvahqmn

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
        - *khoa
        - *sakaki
        - *chiyo
        - *osaka
        - *yomi-strix
