{
  inputs,
  nixpkgs,
  self,
  username,
  host,
  ...
}: {
  imports = [
    ./programs.nix
    ./fonts.nix
    ./user.nix
    ./hardware.nix
    ./stylix.nix
    ./networking.nix
    ./system.nix
    ./security.nix
    ./portals.nix
    ./virtualisation.nix
    ./syncthing.nix
    ./displaymanager.nix
    ./pipewire.nix
    ./services.nix
    ./xserver.nix
    ./steam.nix
    ./thunar.nix
    inputs.stylix.nixosModules.stylix
  ];
}
